version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - echo "Install Prequisites"
      - echo $CROSS_ACCOUNT_ROLE
      - echo $CLOUDFORMATION_EXECUTION_ROLE
      - echo $DESTINATION_ACCOUNT_ID
      - echo $STAGE
      - cd $CODEBUILD_SRC_DIR
      - mkdir ./deployment-package
      - chmod +x aws-profile-setup.sh
      - npm install
      - npm install -g serverless@3.7.4
  build:
    commands:
      - echo "Start Deploy"
      - cd $CODEBUILD_SRC_DIR
      ##################################### Generate serverless package. ###################################
      - . ./aws-profile-setup.sh
      - >
        sls package --package deployment-package --stage $STAGE 
        --param="targetAccountId=$DESTINATION_ACCOUNT_ID" 
        --param="cfnRoleArn=$CLOUDFORMATION_EXECUTION_ROLE"
      - ls deployment-package
      #######################################################################################################
      # Deploy serverless package
      - >
        sls deploy --package deployment-package --stage $STAGE 
        --param="targetAccountId=$DESTINATION_ACCOUNT_ID" 
        --param="cfnRoleArn=$CLOUDFORMATION_EXECUTION_ROLE"
      #######################################################################################################
      #################### Retrieve API Endpoint and pass it on as a build artifact #######################
      - >
        endpoint=$(sls info --verbose --stage $STAGE 
        --param="targetAccountId=$DESTINATION_ACCOUNT_ID" 
        --param="cfnRoleArn=$CLOUDFORMATION_EXECUTION_ROLE" | grep "ServiceEndpoint:")
      - API_URL=$(echo $endpoint | cut -d' ' -f2)
      - echo $API_URL
      - echo $API_URL > api-endpoint.txt
      - cat api-endpoint.txt
      - echo "End Deploy"
      #######################################################################################################
artifacts:
  files:
    # Build Artifact containing API Endpoint
    - api-endpoint.txt
  discard-paths: no
  base-directory: $CODEBUILD_SRC_DIR