service: product-catalog-service

package:
  exclude:
    - ./**
  include:
    - lambda/*.py

custom:
  stage: ${opt:stage, self:provider.stage}
  region: us-east-1
  memorySize: 128

provider:
  name: aws
  runtime: python3.7
  cfnRole: ${param:cfnRoleArn}
  region: ${self:custom.region}
  memorySize: ${self:custom.memorySize}
  environment:
    DYNAMODB_TABLE: ${self:resources.Resources.ProductCatalogDynamoDBTable.Properties.TableName}
  iamRoleStatements:
    - Effect: Allow
      Action: # Allows lambda to interact with dynamodb
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        arn:aws:dynamodb:${self:custom.region}:${param:targetAccountId}:table/${self:resources.Resources.ProductCatalogDynamoDBTable.Properties.TableName}
  stackTags:
    "category": "goldmine"
    "project_name": "cross-account-deployment"

functions:
  create:
    handler: lambda/create-product.handler
    events:
      - http:
          path: product/create
          method: post
  find:
    handler: lambda/find-product.handler
    events:
      - http:
          path: product/find/{id}
          method: get

resources:
  Resources:
    ProductCatalogDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: PRODUCT_CATALOG
